@startuml

left to right direction

skinparam class {
  FontSize 12
  AttributeFontSize 12
  OperationFontSize 12
}
skinparam note {
  FontSize 12
}
skinparam arrow {
  Thickness 1
}
skinparam padding 10
skinparam linetype ortho
skinparam ranksep 50
skinparam nodesep 30

namespace Queues {
    interface QueueInterface {
        +enqueue()
        +dequeue()
    }
    class Queue {
        +enqueue()
        +dequeue()
    }

    QueueInterface <|-- Queue

    note bottom of Queue
      Паттерн: Adapter

      Comment:
      - Queue реализует QueueInterface
    end note
}

@enduml
